// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi MetaGodoc API

    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/org.metagodoc.v1+json

swagger:meta
*/
package restapi
