// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/org.metagodoc.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "MetaGodoc API",
    "version": "0.0.1"
  },
  "paths": {
    "/repository/{repository}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "repository",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/repository"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repository/{repository}/ref/{ref}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "repository",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "ref",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ref"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repository/{repository}/ref/{ref}/package/{package}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "repository",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "ref",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "package",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/package"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "q",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/search_result"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "annotation": {
      "type": "object",
      "properties": {
        "end": {
          "type": "integer",
          "format": "int32"
        },
        "kind": {
          "type": "string",
          "enum": [
            "link",
            "anchor",
            "comment",
            "package-link",
            "builtin"
          ]
        },
        "path_index": {
          "type": "integer",
          "format": "int16"
        },
        "pos": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "code": {
      "type": "object",
      "properties": {
        "annotations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/annotation"
          }
        },
        "paths": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "text": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "integer",
          "format": "uint16"
        }
      }
    },
    "example": {
      "type": "object",
      "properties": {
        "code": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "output": {
          "type": "string"
        },
        "play": {
          "type": "string"
        }
      }
    },
    "file": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "func": {
      "type": "object",
      "properties": {
        "decl": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/example"
          }
        },
        "name": {
          "type": "string"
        },
        "orig": {
          "type": "string"
        },
        "pos": {
          "$ref": "#/definitions/pos"
        },
        "recv": {
          "type": "string"
        }
      }
    },
    "issues": {
      "type": "object",
      "properties": {
        "closed": {
          "type": "integer",
          "format": "int64"
        },
        "open": {
          "type": "integer",
          "format": "int64"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "package": {
      "type": "object",
      "properties": {
        "consts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        },
        "doc": {
          "type": "string"
        },
        "errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/example"
          }
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        },
        "funcs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/func"
          }
        },
        "import_path": {
          "type": "string"
        },
        "imports": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "is_command": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "ref": {
          "type": "string"
        },
        "repository": {
          "type": "string"
        },
        "synopsis": {
          "type": "string"
        },
        "test_imports": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "types": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/type"
          }
        },
        "vars": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        },
        "x_test_imports": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "pos": {
      "type": "object",
      "properties": {
        "file": {
          "type": "integer",
          "format": "int16"
        },
        "line": {
          "type": "integer",
          "format": "int32"
        },
        "n": {
          "type": "integer",
          "format": "uint16"
        }
      }
    },
    "ref": {
      "type": "object",
      "properties": {
        "is_default_branch": {
          "type": "boolean"
        },
        "last_seen_commit": {
          "type": "string",
          "format": "date-time"
        },
        "last_updated": {
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "type": "string"
        },
        "packages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/package"
          }
        },
        "ref_type": {
          "type": "string",
          "enum": [
            "branch",
            "tag"
          ]
        },
        "repository": {
          "type": "string"
        }
      }
    },
    "repository": {
      "type": "object",
      "properties": {
        "about": {
          "type": "object",
          "properties": {
            "content": {
              "type": "string"
            },
            "content_type": {
              "type": "string"
            }
          }
        },
        "created": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "forks": {
          "type": "integer",
          "format": "int64"
        },
        "full_name": {
          "type": "string"
        },
        "issues": {
          "$ref": "#/definitions/issues"
        },
        "last_crawled": {
          "type": "string",
          "format": "date-time"
        },
        "last_updated": {
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        },
        "primary_url": {
          "type": "string",
          "format": "uri"
        },
        "pull_requests": {
          "$ref": "#/definitions/issues"
        },
        "refs": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "is_default_branch": {
                "type": "boolean"
              },
              "name": {
                "type": "string"
              },
              "ref_type": {
                "type": "string",
                "enum": [
                  "branch",
                  "tag"
                ]
              }
            }
          }
        },
        "stars": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string",
          "enum": [
            "active",
            "dead-end-fork",
            "quick-fork",
            "no-recent-commits",
            "inactive"
          ]
        },
        "vcs": {
          "type": "string",
          "enum": [
            "bzr",
            "git",
            "hg",
            "svn"
          ]
        }
      }
    },
    "search_result": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "item_type": {
                "type": "string",
                "enum": [
                  "repository",
                  "package"
                ]
              },
              "package": {
                "$ref": "#/definitions/package"
              },
              "repository": {
                "$ref": "#/definitions/repository"
              },
              "url": {
                "type": "string",
                "format": "uri"
              },
              "weight": {
                "type": "integer",
                "format": "int64"
              }
            }
          }
        }
      }
    },
    "type": {
      "type": "object",
      "properties": {
        "consts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        },
        "decl": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/example"
          }
        },
        "funcs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/func"
          }
        },
        "methods": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/func"
          }
        },
        "name": {
          "type": "string"
        },
        "pos": {
          "$ref": "#/definitions/pos"
        },
        "vars": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        }
      }
    },
    "value": {
      "type": "object",
      "properties": {
        "decl": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "pos": {
          "$ref": "#/definitions/pos"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/org.metagodoc.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "MetaGodoc API",
    "version": "0.0.1"
  },
  "paths": {
    "/repository/{repository}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "repository",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/repository"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repository/{repository}/ref/{ref}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "repository",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "ref",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ref"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/repository/{repository}/ref/{ref}/package/{package}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "repository",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "ref",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "package",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/package"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/search": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "q",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/search_result"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "annotation": {
      "type": "object",
      "properties": {
        "end": {
          "type": "integer",
          "format": "int32"
        },
        "kind": {
          "type": "string",
          "enum": [
            "link",
            "anchor",
            "comment",
            "package-link",
            "builtin"
          ]
        },
        "path_index": {
          "type": "integer",
          "format": "int16"
        },
        "pos": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "code": {
      "type": "object",
      "properties": {
        "annotations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/annotation"
          }
        },
        "paths": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "text": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "integer",
          "format": "uint16"
        }
      }
    },
    "example": {
      "type": "object",
      "properties": {
        "code": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "output": {
          "type": "string"
        },
        "play": {
          "type": "string"
        }
      }
    },
    "file": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "func": {
      "type": "object",
      "properties": {
        "decl": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/example"
          }
        },
        "name": {
          "type": "string"
        },
        "orig": {
          "type": "string"
        },
        "pos": {
          "$ref": "#/definitions/pos"
        },
        "recv": {
          "type": "string"
        }
      }
    },
    "issues": {
      "type": "object",
      "properties": {
        "closed": {
          "type": "integer",
          "format": "int64"
        },
        "open": {
          "type": "integer",
          "format": "int64"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "package": {
      "type": "object",
      "properties": {
        "consts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        },
        "doc": {
          "type": "string"
        },
        "errors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/example"
          }
        },
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/file"
          }
        },
        "funcs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/func"
          }
        },
        "import_path": {
          "type": "string"
        },
        "imports": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "is_command": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "ref": {
          "type": "string"
        },
        "repository": {
          "type": "string"
        },
        "synopsis": {
          "type": "string"
        },
        "test_imports": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "types": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/type"
          }
        },
        "vars": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        },
        "x_test_imports": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "pos": {
      "type": "object",
      "properties": {
        "file": {
          "type": "integer",
          "format": "int16"
        },
        "line": {
          "type": "integer",
          "format": "int32"
        },
        "n": {
          "type": "integer",
          "format": "uint16"
        }
      }
    },
    "ref": {
      "type": "object",
      "properties": {
        "is_default_branch": {
          "type": "boolean"
        },
        "last_seen_commit": {
          "type": "string",
          "format": "date-time"
        },
        "last_updated": {
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "type": "string"
        },
        "packages": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/package"
          }
        },
        "ref_type": {
          "type": "string",
          "enum": [
            "branch",
            "tag"
          ]
        },
        "repository": {
          "type": "string"
        }
      }
    },
    "repository": {
      "type": "object",
      "properties": {
        "about": {
          "$ref": "#/definitions/repositoryAbout"
        },
        "created": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "forks": {
          "type": "integer",
          "format": "int64"
        },
        "full_name": {
          "type": "string"
        },
        "issues": {
          "$ref": "#/definitions/issues"
        },
        "last_crawled": {
          "type": "string",
          "format": "date-time"
        },
        "last_updated": {
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        },
        "primary_url": {
          "type": "string",
          "format": "uri"
        },
        "pull_requests": {
          "$ref": "#/definitions/issues"
        },
        "refs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/repositoryRefsItems"
          }
        },
        "stars": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string",
          "enum": [
            "active",
            "dead-end-fork",
            "quick-fork",
            "no-recent-commits",
            "inactive"
          ]
        },
        "vcs": {
          "type": "string",
          "enum": [
            "bzr",
            "git",
            "hg",
            "svn"
          ]
        }
      }
    },
    "repositoryAbout": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "content_type": {
          "type": "string"
        }
      },
      "x-go-gen-location": "models"
    },
    "repositoryRefsItems": {
      "type": "object",
      "properties": {
        "is_default_branch": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "ref_type": {
          "type": "string",
          "enum": [
            "branch",
            "tag"
          ]
        }
      },
      "x-go-gen-location": "models"
    },
    "searchResultResultsItems": {
      "type": "object",
      "properties": {
        "item_type": {
          "type": "string",
          "enum": [
            "repository",
            "package"
          ]
        },
        "package": {
          "$ref": "#/definitions/package"
        },
        "repository": {
          "$ref": "#/definitions/repository"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "weight": {
          "type": "integer",
          "format": "int64"
        }
      },
      "x-go-gen-location": "models"
    },
    "search_result": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/searchResultResultsItems"
          }
        }
      }
    },
    "type": {
      "type": "object",
      "properties": {
        "consts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        },
        "decl": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/example"
          }
        },
        "funcs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/func"
          }
        },
        "methods": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/func"
          }
        },
        "name": {
          "type": "string"
        },
        "pos": {
          "$ref": "#/definitions/pos"
        },
        "vars": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/value"
          }
        }
      }
    },
    "value": {
      "type": "object",
      "properties": {
        "decl": {
          "$ref": "#/definitions/code"
        },
        "doc": {
          "type": "string"
        },
        "pos": {
          "$ref": "#/definitions/pos"
        }
      }
    }
  }
}`))
}
