// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRepositoryRepositoryRefRefHandlerFunc turns a function with the right signature into a get repository repository ref ref handler
type GetRepositoryRepositoryRefRefHandlerFunc func(GetRepositoryRepositoryRefRefParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRepositoryRepositoryRefRefHandlerFunc) Handle(params GetRepositoryRepositoryRefRefParams) middleware.Responder {
	return fn(params)
}

// GetRepositoryRepositoryRefRefHandler interface for that can handle valid get repository repository ref ref params
type GetRepositoryRepositoryRefRefHandler interface {
	Handle(GetRepositoryRepositoryRefRefParams) middleware.Responder
}

// NewGetRepositoryRepositoryRefRef creates a new http.Handler for the get repository repository ref ref operation
func NewGetRepositoryRepositoryRefRef(ctx *middleware.Context, handler GetRepositoryRepositoryRefRefHandler) *GetRepositoryRepositoryRefRef {
	return &GetRepositoryRepositoryRefRef{Context: ctx, Handler: handler}
}

/*GetRepositoryRepositoryRefRef swagger:route GET /repository/{repository}/ref/{ref} getRepositoryRepositoryRefRef

GetRepositoryRepositoryRefRef get repository repository ref ref API

*/
type GetRepositoryRepositoryRefRef struct {
	Context *middleware.Context
	Handler GetRepositoryRepositoryRefRefHandler
}

func (o *GetRepositoryRepositoryRefRef) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRepositoryRepositoryRefRefParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
