// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoryRepositoryParams creates a new GetRepositoryRepositoryParams object
// no default values defined in spec.
func NewGetRepositoryRepositoryParams() GetRepositoryRepositoryParams {

	return GetRepositoryRepositoryParams{}
}

// GetRepositoryRepositoryParams contains all the bound params for the get repository repository operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetRepositoryRepository
type GetRepositoryRepositoryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Repository string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRepositoryRepositoryParams() beforehand.
func (o *GetRepositoryRepositoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRepository, rhkRepository, _ := route.Params.GetOK("repository")
	if err := o.bindRepository(rRepository, rhkRepository, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRepositoryRepositoryParams) bindRepository(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Repository = raw

	return nil
}
