// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/autarch/metagodoc/api/models"
)

// GetRepositoryRepositoryOKCode is the HTTP code returned for type GetRepositoryRepositoryOK
const GetRepositoryRepositoryOKCode int = 200

/*GetRepositoryRepositoryOK OK

swagger:response getRepositoryRepositoryOK
*/
type GetRepositoryRepositoryOK struct {

	/*
	  In: Body
	*/
	Payload *models.Repository `json:"body,omitempty"`
}

// NewGetRepositoryRepositoryOK creates GetRepositoryRepositoryOK with default headers values
func NewGetRepositoryRepositoryOK() *GetRepositoryRepositoryOK {

	return &GetRepositoryRepositoryOK{}
}

// WithPayload adds the payload to the get repository repository o k response
func (o *GetRepositoryRepositoryOK) WithPayload(payload *models.Repository) *GetRepositoryRepositoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repository repository o k response
func (o *GetRepositoryRepositoryOK) SetPayload(payload *models.Repository) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRepositoryRepositoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRepositoryRepositoryDefault error

swagger:response getRepositoryRepositoryDefault
*/
type GetRepositoryRepositoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRepositoryRepositoryDefault creates GetRepositoryRepositoryDefault with default headers values
func NewGetRepositoryRepositoryDefault(code int) *GetRepositoryRepositoryDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRepositoryRepositoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get repository repository default response
func (o *GetRepositoryRepositoryDefault) WithStatusCode(code int) *GetRepositoryRepositoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get repository repository default response
func (o *GetRepositoryRepositoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get repository repository default response
func (o *GetRepositoryRepositoryDefault) WithPayload(payload *models.Error) *GetRepositoryRepositoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repository repository default response
func (o *GetRepositoryRepositoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRepositoryRepositoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
