// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRepositoryRepositoryRefRefPackagePackageHandlerFunc turns a function with the right signature into a get repository repository ref ref package package handler
type GetRepositoryRepositoryRefRefPackagePackageHandlerFunc func(GetRepositoryRepositoryRefRefPackagePackageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRepositoryRepositoryRefRefPackagePackageHandlerFunc) Handle(params GetRepositoryRepositoryRefRefPackagePackageParams) middleware.Responder {
	return fn(params)
}

// GetRepositoryRepositoryRefRefPackagePackageHandler interface for that can handle valid get repository repository ref ref package package params
type GetRepositoryRepositoryRefRefPackagePackageHandler interface {
	Handle(GetRepositoryRepositoryRefRefPackagePackageParams) middleware.Responder
}

// NewGetRepositoryRepositoryRefRefPackagePackage creates a new http.Handler for the get repository repository ref ref package package operation
func NewGetRepositoryRepositoryRefRefPackagePackage(ctx *middleware.Context, handler GetRepositoryRepositoryRefRefPackagePackageHandler) *GetRepositoryRepositoryRefRefPackagePackage {
	return &GetRepositoryRepositoryRefRefPackagePackage{Context: ctx, Handler: handler}
}

/*GetRepositoryRepositoryRefRefPackagePackage swagger:route GET /repository/{repository}/ref/{ref}/package/{package} getRepositoryRepositoryRefRefPackagePackage

GetRepositoryRepositoryRefRefPackagePackage get repository repository ref ref package package API

*/
type GetRepositoryRepositoryRefRefPackagePackage struct {
	Context *middleware.Context
	Handler GetRepositoryRepositoryRefRefPackagePackageHandler
}

func (o *GetRepositoryRepositoryRefRefPackagePackage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRepositoryRepositoryRefRefPackagePackageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
