// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/autarch/metagodoc/api/models"
)

// GetSearchOKCode is the HTTP code returned for type GetSearchOK
const GetSearchOKCode int = 200

/*GetSearchOK OK

swagger:response getSearchOK
*/
type GetSearchOK struct {

	/*
	  In: Body
	*/
	Payload []*models.SearchResult `json:"body,omitempty"`
}

// NewGetSearchOK creates GetSearchOK with default headers values
func NewGetSearchOK() *GetSearchOK {

	return &GetSearchOK{}
}

// WithPayload adds the payload to the get search o k response
func (o *GetSearchOK) WithPayload(payload []*models.SearchResult) *GetSearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get search o k response
func (o *GetSearchOK) SetPayload(payload []*models.SearchResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.SearchResult, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetSearchDefault error

swagger:response getSearchDefault
*/
type GetSearchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetSearchDefault creates GetSearchDefault with default headers values
func NewGetSearchDefault(code int) *GetSearchDefault {
	if code <= 0 {
		code = 500
	}

	return &GetSearchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get search default response
func (o *GetSearchDefault) WithStatusCode(code int) *GetSearchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get search default response
func (o *GetSearchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get search default response
func (o *GetSearchDefault) WithPayload(payload *models.Error) *GetSearchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get search default response
func (o *GetSearchDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSearchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
