// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoryRepositoryRefRefPackagePackageParams creates a new GetRepositoryRepositoryRefRefPackagePackageParams object
// no default values defined in spec.
func NewGetRepositoryRepositoryRefRefPackagePackageParams() GetRepositoryRepositoryRefRefPackagePackageParams {

	return GetRepositoryRepositoryRefRefPackagePackageParams{}
}

// GetRepositoryRepositoryRefRefPackagePackageParams contains all the bound params for the get repository repository ref ref package package operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetRepositoryRepositoryRefRefPackagePackage
type GetRepositoryRepositoryRefRefPackagePackageParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	Package string
	/*
	  Required: true
	  In: path
	*/
	Ref string
	/*
	  Required: true
	  In: path
	*/
	Repository string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRepositoryRepositoryRefRefPackagePackageParams() beforehand.
func (o *GetRepositoryRepositoryRefRefPackagePackageParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rPackage, rhkPackage, _ := route.Params.GetOK("package")
	if err := o.bindPackage(rPackage, rhkPackage, route.Formats); err != nil {
		res = append(res, err)
	}

	rRef, rhkRef, _ := route.Params.GetOK("ref")
	if err := o.bindRef(rRef, rhkRef, route.Formats); err != nil {
		res = append(res, err)
	}

	rRepository, rhkRepository, _ := route.Params.GetOK("repository")
	if err := o.bindRepository(rRepository, rhkRepository, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRepositoryRepositoryRefRefPackagePackageParams) bindPackage(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Package = raw

	return nil
}

func (o *GetRepositoryRepositoryRefRefPackagePackageParams) bindRef(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Ref = raw

	return nil
}

func (o *GetRepositoryRepositoryRefRefPackagePackageParams) bindRepository(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Repository = raw

	return nil
}
