// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Func func
// swagger:model func
type Func struct {

	// decl
	Decl *Code `json:"decl,omitempty"`

	// doc
	Doc string `json:"doc,omitempty"`

	// examples
	Examples []*Example `json:"examples"`

	// name
	Name string `json:"name,omitempty"`

	// orig
	Orig string `json:"orig,omitempty"`

	// pos
	Pos *Pos `json:"pos,omitempty"`

	// recv
	Recv string `json:"recv,omitempty"`
}

// Validate validates this func
func (m *Func) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDecl(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateExamples(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePos(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Func) validateDecl(formats strfmt.Registry) error {

	if swag.IsZero(m.Decl) { // not required
		return nil
	}

	if m.Decl != nil {

		if err := m.Decl.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("decl")
			}
			return err
		}

	}

	return nil
}

func (m *Func) validateExamples(formats strfmt.Registry) error {

	if swag.IsZero(m.Examples) { // not required
		return nil
	}

	for i := 0; i < len(m.Examples); i++ {

		if swag.IsZero(m.Examples[i]) { // not required
			continue
		}

		if m.Examples[i] != nil {

			if err := m.Examples[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("examples" + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

func (m *Func) validatePos(formats strfmt.Registry) error {

	if swag.IsZero(m.Pos) { // not required
		return nil
	}

	if m.Pos != nil {

		if err := m.Pos.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pos")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Func) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Func) UnmarshalBinary(b []byte) error {
	var res Func
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
