// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Value value
// swagger:model value
type Value struct {

	// decl
	Decl *Code `json:"decl,omitempty"`

	// doc
	Doc string `json:"doc,omitempty"`

	// pos
	Pos *Pos `json:"pos,omitempty"`
}

// Validate validates this value
func (m *Value) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDecl(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePos(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Value) validateDecl(formats strfmt.Registry) error {

	if swag.IsZero(m.Decl) { // not required
		return nil
	}

	if m.Decl != nil {

		if err := m.Decl.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("decl")
			}
			return err
		}

	}

	return nil
}

func (m *Value) validatePos(formats strfmt.Registry) error {

	if swag.IsZero(m.Pos) { // not required
		return nil
	}

	if m.Pos != nil {

		if err := m.Pos.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pos")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Value) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Value) UnmarshalBinary(b []byte) error {
	var res Value
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
